---
version: 0.2

phases:
  install:
    commands:
      - 'gem install bundler'
      - 'bundle install --with test'
  build:
    commands:
       - 'bundle exec rails test'

artifacts:
  files:
    - '**/*'
  name: zombie_battleground-browser-$(date +%Y-%m-%d)
